# **Fundamentos de NumPy: arrays y computación vectorizada**


In [1]:
from google.colab import drive
drive.mount("/content/drive")

import sys
sys.path.append("/content/drive/MyDrive/utils")

from colab_git import setup, push

setup(
    project_dir="/content/drive/MyDrive/Colab Notebooks/Libro_Python_para_analisis_de_datos",
    repo="data_analyst",
)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Repositorio listo: https://github.com/tuliobast/data_analyst.git


In [2]:
import numpy as np
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

1.13 ms ± 82.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

68.8 ms ± 16.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## **El ndarray de NumPy: un objeto array multidimensional**


In [5]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
# numpy facilita las operaciones con array
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
#  a diferencia de python
lista = [[1.5, -0.1, 3], [0, -3, 6.5]]
lista * 10

[[1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5],
 [1.5, -0.1, 3],
 [0, -3, 6.5]]

In [9]:
lista + lista

[[1.5, -0.1, 3], [0, -3, 6.5], [1.5, -0.1, 3], [0, -3, 6.5]]

### **Creando ndarrays**

In [26]:
# creando array a partir de listas
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

data2 = [[1, 2, 3], [4, 5, 6],[7, 8, 9]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim) # imprime las dimenciones del array
print(arr2.shape) # imprime las columnas y filas del array

# array de ceros
print(np.zeros(10))
print(f'zero array(3,6): {np.zeros((3, 6))}')

# array de unos
print(np.ones(10))
print(f'one array(3,6): {np.ones((3, 6))}')
np.ones(())

# array vacio
print(f'empty array: {np.empty((1, 2, 3, 4))}')

# array de un rango
print(f'range array: {np.arange(15)}')

# array de 5
print(f'full array: {np.full((3, 5), 5, dtype=float)}')

# array eye
print(f'eye array: {np.eye(5,2,dtype=str)}')

# array identity
print(f'identity array: {np.identity(6, dtype=bool)}')


[6.  7.5 8.  0.  1. ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
zero array(3,6): [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
one array(3,6): [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
empty array: [[[[-0.25 -0.5   0.   -0.25]
   [ 0.25 -0.5   0.5  -0.25]
   [ 0.25  0.    0.5   0.25]]

  [[ 0.25  0.5   0.    0.25]
   [-0.25  0.5  -0.5   0.25]
   [-0.25  0.   -0.5  -0.25]]]]
range array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
full array: [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
eye array: [['1' '']
 ['' '1']
 ['' '']
 ['' '']
 ['' '']]
identity array: [[ True False False False False False]
 [False  True False False False False]
 [False False  True False False False]
 [False False False  True False False]
 [False False False False  True False]
 [False False False False False  True]]


In [28]:
# para cambiar el tipo de dato contenido en el array astype()
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

# los tipos de datos string se declaran con .bytes_
string_arr = np.array(
['1.99', '-9.6', '42'], dtype=np.bytes_)
print(string_arr)
print(string_arr.dtype)
#

int64
float64
[b'1.99' b'-9.6' b'42']
|S4


### **Aritmética con arrays NumPy**
los array en numpy permiten realizar operaciones aritmenticas elemento por elemento si necesidad de un bocle for

In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# las operaciones con valores escalares se propagan a todo el array
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

####indexado

In [32]:
arr = np.arange(10)
arr[5:8] = 64
arr
# en los arrays los datos no se copian, y que cualquier modificación de la vista se verá reflejada en el array de origen.
arr_slice = arr[5:8]
arr_slice

array([64, 64, 64])

In [33]:
arr_slice[1] = 12
arr

array([ 0,  1,  2,  3,  4, 64, 12, 64,  8,  9])

####indexado con corte

In [52]:
arr
print(f'''array:
{arr[1:6]}
''')
# cortar un eje del array
print(f'''array2d:
{arr2}
dimenciones:
{len(arr2.shape)}''')

print(f'''
arr2[:2]:
{arr2[:2]}
dimenciones:
{len(arr2[:2])}
''')

# realizar varios cortes se obtiene un array del mismo numero de dimenciones
print(f'''arr2[:2,1:]:
{arr2[:2,1:]}
dimenciones:
{len(arr2[:2,1:].shape)}
''')


# para reducir las dimenciones del array
print(f'''
arr2[1,2:]
''')

array:
[ 1  2  3  4 64]

array2d: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimenciones: 
2

arr2[:2]:
[[1 2 3]
 [4 5 6]]
dimenciones:
2
arr2[:2,1:]:
[[2 3]
 [5 6]]
dimenciones:
2


arr2[1,2:]



In [17]:
push("creando cap 4")

✅ Push realizado correctamente.
